package ar.com.smg.entities;
// Generated 07-feb-2017 13:05:04 by Hibernate Tools 5.1.0.Final

/**
 * Aplicaciones generated by hbm2java
 */
public class Aplicacion implements java.io.Serializable {

	private int idAplicacion;
	private String descripcion;

	public Aplicacion() {
	}

	public Aplicacion(int idAplicacion, String descripcion) {
		this.idAplicacion = idAplicacion;
		this.descripcion = descripcion;
	}

	public int getIdAplicacion() {
		return this.idAplicacion;
	}

	public void setIdAplicacion(int idAplicacion) {
		this.idAplicacion = idAplicacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
