package ar.com.smg.entities;
// Generated 07-feb-2017 13:05:04 by Hibernate Tools 5.1.0.Final

/**
 * Basedeconocimientos generated by hbm2java
 */
public class BaseDeConocimiento implements java.io.Serializable {

	private String identificador;
	private String analisis;
	private String solucion;

	public BaseDeConocimiento() {
	}

	public BaseDeConocimiento(String identificador, String analisis, String solucion) {
		this.identificador = identificador;
		this.analisis = analisis;
		this.solucion = solucion;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public String getAnalisis() {
		return this.analisis;
	}

	public void setAnalisis(String analisis) {
		this.analisis = analisis;
	}

	public String getSolucion() {
		return this.solucion;
	}

	public void setSolucion(String solucion) {
		this.solucion = solucion;
	}

}
