package ar.com.smg.entities;
// Generated 07-feb-2017 13:05:04 by Hibernate Tools 5.1.0.Final

import java.util.Date;

/**
 * Casos generated by hbm2java
 */
public class Caso implements java.io.Serializable {

	private int idCaso;
	private String descripcion;
	private int idEstado;
	private int idSeveridad;
	private int idUsuario;
	private Date fechaRegistro;
	private Date fechaCierre;
	private int idSoporte;
	private int idTipoCaso;
	private String solicitadoPor;
	private String identificador;
	private int idModulo;
	private int idAplicacion;

	public Caso() {
	}

	public Caso(int idCaso, String descripcion, int idEstado, int idSeveridad, int idUsuario, Date fechaRegistro,
			Date fechaCierre, int idSoporte, int idTipoCaso, String solicitadoPor, String identificador, int idModulo,
			int idAplicacion) {
		this.idCaso = idCaso;
		this.descripcion = descripcion;
		this.idEstado = idEstado;
		this.idSeveridad = idSeveridad;
		this.idUsuario = idUsuario;
		this.fechaRegistro = fechaRegistro;
		this.fechaCierre = fechaCierre;
		this.idSoporte = idSoporte;
		this.idTipoCaso = idTipoCaso;
		this.solicitadoPor = solicitadoPor;
		this.identificador = identificador;
		this.idModulo = idModulo;
		this.idAplicacion = idAplicacion;
	}

	public int getIdCaso() {
		return this.idCaso;
	}

	public void setIdCaso(int idCaso) {
		this.idCaso = idCaso;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public int getIdSeveridad() {
		return this.idSeveridad;
	}

	public void setIdSeveridad(int idSeveridad) {
		this.idSeveridad = idSeveridad;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public int getIdSoporte() {
		return this.idSoporte;
	}

	public void setIdSoporte(int idSoporte) {
		this.idSoporte = idSoporte;
	}

	public int getIdTipoCaso() {
		return this.idTipoCaso;
	}

	public void setIdTipoCaso(int idTipoCaso) {
		this.idTipoCaso = idTipoCaso;
	}

	public String getSolicitadoPor() {
		return this.solicitadoPor;
	}

	public void setSolicitadoPor(String solicitadoPor) {
		this.solicitadoPor = solicitadoPor;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public int getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(int idModulo) {
		this.idModulo = idModulo;
	}

	public int getIdAplicacion() {
		return this.idAplicacion;
	}

	public void setIdAplicacion(int idAplicacion) {
		this.idAplicacion = idAplicacion;
	}

}
