package ar.com.smg.entities;
// Generated 07-feb-2017 13:05:04 by Hibernate Tools 5.1.0.Final

/**
 * Cierrescaso generated by hbm2java
 */
public class CierreCaso implements java.io.Serializable {

	private int idCierreCaso;
	private int descripcion;
	private int idTipoCaso;
	private boolean habilitado;

	public CierreCaso() {
	}

	public CierreCaso(int idCierreCaso, int descripcion, int idTipoCaso, boolean habilitado) {
		this.idCierreCaso = idCierreCaso;
		this.descripcion = descripcion;
		this.idTipoCaso = idTipoCaso;
		this.habilitado = habilitado;
	}

	public int getIdCierreCaso() {
		return this.idCierreCaso;
	}

	public void setIdCierreCaso(int idCierreCaso) {
		this.idCierreCaso = idCierreCaso;
	}

	public int getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(int descripcion) {
		this.descripcion = descripcion;
	}

	public int getIdTipoCaso() {
		return this.idTipoCaso;
	}

	public void setIdTipoCaso(int idTipoCaso) {
		this.idTipoCaso = idTipoCaso;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

}
