package ar.com.smg.entities;
// Generated 07-feb-2017 13:05:04 by Hibernate Tools 5.1.0.Final

/**
 * Estadoscaso generated by hbm2java
 */
public class EstadoCaso implements java.io.Serializable {

	private int idEstado;
	private int descripcion;

	public EstadoCaso() {
	}

	public EstadoCaso(int idEstado, int descripcion) {
		this.idEstado = idEstado;
		this.descripcion = descripcion;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public int getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(int descripcion) {
		this.descripcion = descripcion;
	}

}
