package ar.com.smg.entities;
// Generated 07-feb-2017 13:05:04 by Hibernate Tools 5.1.0.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private String nombre;
	private String isStk;
	private int jornada;
	private boolean habillitado;
	private int password;

	public Usuario() {
	}

	public Usuario(int idUsuario, String nombre, String isStk, int jornada, boolean habillitado, int password) {
		this.idUsuario = idUsuario;
		this.nombre = nombre;
		this.isStk = isStk;
		this.jornada = jornada;
		this.habillitado = habillitado;
		this.password = password;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIsStk() {
		return this.isStk;
	}

	public void setIsStk(String isStk) {
		this.isStk = isStk;
	}

	public int getJornada() {
		return this.jornada;
	}

	public void setJornada(int jornada) {
		this.jornada = jornada;
	}

	public boolean isHabillitado() {
		return this.habillitado;
	}

	public void setHabillitado(boolean habillitado) {
		this.habillitado = habillitado;
	}

	public int getPassword() {
		return this.password;
	}

	public void setPassword(int password) {
		this.password = password;
	}

}
